### ISSUE TITLE
Make card animation start when removing

### ISSUE THREAD

**Issue by feinstein** [hongduc6/stacked_list_carousel#3]
When I discard the top card, there's a delay for the other cards to start animating, it would be better if they animated together

**Comment by curtis6636** [comment]
Thank you for your suggestion, @feinstein.

Unfortunately, in my initial design, the animations for the outermost card flying away and reordering are interdependent, making it difficult to improve at this time. However, I will explore the possibility of redesigning these animations in the future. Sincerely.

**Comment by feinstein** [comment]
@curtisluu-66 I looked at your source code and I was able to make this work but just removing this await:

![image](https://github.com/user-attachments/assets/1bb1484a-6bb8-4de0-a796-a643dbc87b78)

This will trigger all the animations at the same time, as you won't await for the outer card animation to complete.

**Comment by curtis6636** [comment]
I've tried it. But as i said before, the both animations are interdependent, so even when we remove await, it wont work as expected.

**Comment by feinstein** [comment]
It worked for me, I will fork your code then and use it without the await

**Comment by curtis6636** [comment]
Glad to hear that. In my case, the outermost card just disappear immediately without smooth transition

**Comment by feinstein** [comment]
maybe with my configurations it works, I am not sure, but thanks
