### ISSUE TITLE
Disable loop animation

### ISSUE THREAD

**Issue by feinstein** [hongduc6/stacked_list_carousel#4]
I want a loop carousel, but I don't want it to automatically loop. My solution now is to give it a huge duration, but it would be better if we could control this with maybe a `bool` or a `Duration.zero`.

**Comment by curtis6636** [comment]
Certainly @feinstein , i added a customization fields in version 1.0.2+1. Feel free to request any customizations you need!

**Comment by feinstein** [comment]
Why +1? This should be 1.0.3 as you are adding a feature that doesn't impact the api

**Comment by feinstein** [comment]
@curtisluu-66 have you pushed your changes to the repo?

**Comment by curtis6636** [comment]
I already did @feinstein . I did not increase the minor version as the change is minimal :D

**Comment by feinstein** [comment]
@curtisluu-66 that's not how semantic versioning works, please take a read at https://semver.org/spec/v2.0.0-rc.1.html as that's the expected versioning that dart packages should follow, as documented here https://dart.dev/tools/pub/versioning.

I was even wrong, this should be `1.1.0` as:

> Bug fixes not affecting the API increment the patch version, backwards compatible API additions/changes increment the minor version, and backwards incompatible API changes increment the major version.

So this would require a `minor` version increase, as this is an API change that is backwards compatible.

Sticking to semver is important, because dart uses this to automatically upgrade packages inside apps, and if packages don't follow this, dart may update a package with a breaking change and break the app.

**Comment by curtis6636** [comment]
Wow, thank you for your support. I wasn't notice that, that's a new knowledge to me. Appreciate!

**Comment by feinstein** [comment]
no worries
